TEAM = NOBODY
VERSION = 1
HANDINDIR = /afs/cs/academic/class/15213-f02/L7/handin

CC = gcc
CFLAGS = -Wall -g 

OBJS = proxy.o csapp.o -lpthread


all: proxy

proxy: $(OBJS)

csapp.o: csapp.c
	$(CC) $(CFLAGS) -c csapp.c

proxy.o: proxy.c
	$(CC) $(CFLAGS) -c proxy.c

handin:
	cp -i proxy.c /home/prof/dropbox/proxylab-`whoami`-proxy.c

clean:
	rm -f *~ *.o proxy core

